# include <iostream>
using namespae std;
int main()
{
    //GET COMPUTER NUMBER
    //GET PLAYER NUMBER
    //PLAYER NUMBER = COMPUTER NUMBER?
    //IF PLAYER NUMBER > COMPUTER NUMBER SHOW 'LOWER'& -1 POINT
    //IF PLAYER NUMBER < COMPUTER NUMBER SHOW 'HIGHER'& -1 POINT
    //IF PLAYER NUMBER = COMPUTER NUMBER SHOW 'WIN!'
    //IF 'WIN!' AWARD PLAYER 10 POINTS
}